export const SET_ERRORS = 'SET_ERRORS';

export const LOGIN_USER_START = 'LOGIN_USER_START';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UNSET_CURRENT_USER = 'UNSET_CURRENT_USER';
export const SIGN_UP_START = 'SIGN_UP_START';
export const SIGN_UP_END = 'SIGN_UP_END';
